# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.6"

# services:
#   shell:
#     image: hyperledger/sawtooth-shell
#     container_name: sawtooth-shell
#     entrypoint: "bash -c \"\
#       sawtooth keygen && \
#       tail -f /dev/null \
#       \""

  # influxdb:
  #   image: influxdb
  #   container_name: sawtooth-stats-influxdb-default
  #   ports:
  #     - "8086:8086"
  #   volumes:
  #     - ./monitor:/var/lib/influxdb
  #   stop_signal: SIGKILL

  # telegraf:
  #   image: telegraf
  #   container_name: sawtooth-stats-telegraf-default
  #   volumes:
  #     - ./telegraf.conf:/etc/telegraf/telegraf.conf
  #   stop_signal: SIGKILL

  # chronograf:
  #   image: chronograf
  #   container_name: sawtooth-stats-chronograf-default
  #   ports:
  #     - "8888:8888"
  #   stop_signal: SIGKILL

  # kapacitor:
  #   image: kapacitor
  #   container_name: sawtooth-stats-kapacitor-default
  #   ports:
  #     - "9092:9092"
  #   volumes:
  #     - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf
  #   stop_signal: SIGKILL

  # grafana:
  #   image: grafana
  #   container_name: sawtooth-stats-grafana-default
  #   ports:
  #     - "80:3000"
  #   stop_signal: SIGKILL

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.1.4
    container_name: settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:1.1.4
    container_name: validator
    hostname: sawtooth-validator
    expose:
      - 4004
      - 8800
      - 5050
    ports:
      - "4004:4004"
      - "5050:5050"
      - "8800:8800"
    command: "bash -c \"\
      sawadm keygen && \
      sawset genesis \
      -k /etc/sawtooth/keys/validator.priv \
      -o config-genesis.batch && \
      sawadm genesis \
      config-genesis.batch && \
      sawtooth-validator -v \
      --bind network:tcp://eth0:8800 \
      --bind component:tcp://eth0:4004 \
      --bind consensus:tcp://eth0:5050 \
      --peering dynamic \
      --endpoint tcp://validator:8800 \
      --scheduler parallel \
      --opentsdb-db metrics \
      --opentsdb-url http://influxdb:8086 \
      --network-auth trust \
      \""
    environment:
      PYTHONPATH: "/project/sawtooth-core/consensus/poet/common:\
        /project/sawtooth-core/consensus/poet/simulator:\
        /project/sawtooth-core/consensus/poet/core"
    stop_signal: SIGKILL

  fruitchain-tp-go:
    image: bacbia/sawtooth-fruitchain-tp-go:latest
    container_name: sawtooth-fruitchain-tp-go-default
    depends_on:
      - validator
    command: fruitchain-tp-go -vv -C tcp://validator:4004

  devmode-rust:
    image: hyperledger/sawtooth-devmode-engine-rust:1.1.4
    container_name: devmode-engine-rust
    depends_on:
      - validator
    entrypoint: devmode-engine-rust -vv --connect tcp://validator:5050
    stop_signal: SIGKILL

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.1.4
    container_name: rest-api
    expose:
      - 4004
      - 8008
    ports:
      - "8008:8008"
    command: "bash -c \"
      sawtooth-rest-api -vvv \
      --connect tcp://validator:4004 \
      --bind rest-api:8008
      \""
    stop_signal: SIGKILL

  influxdb:
    image: socoboy/installed-sawtooth-stats-influxdb:1.2.1
    container_name: influxdb
    ports:
      - "8086:8086"
    stop_signal: SIGKILL

  grafana:
    image: socoboy/installed-sawtooth-stats-grafana:1.2.1
    container_name: grafana
    ports:
      - "3000:3000"
    stop_signal: SIGKILL

  # intkey-tp:
  #   image: hyperledger/sawtooth-intkey-tp-python
  #   container_name: intkey-tp
  #   expose:
  #     - 4004
  #   command: intkey-tp-python -vv -C tcp://validator:4004
  #   stop_signal: SIGKILL
  # block-info-tp:
  #   image: sawtooth-block-info-tp:1.1.2
  #   container_name: block-info-tp
  #   command: block-info-tp -vvv -C tcp://validator:4004
  #   stop_signal: SIGKILL
